datagrid:
    document-grid:
        options:
            entityHint: document
            manageFilters: false
        source:
            type:               pim_datasource_default
            entity:             Pim\Bundle\TextmasterBundle\Entity\Document
            repository_method:  createDatagridQueryBuilder
        columns:
            productIdentifier:
                label: pim_textmaster.field.label.product_identifier
            productLabel:
                label: pim_textmaster.field.label.product_label
            language:
                label: pim_textmaster.field.label.language
            status:
                label: pim_textmaster.field.label.status
            updatedAt:
                label: pim_textmaster.field.label.updated_at
                frontend_type: date
        properties:
            edit_product:
                type: url
                route: pim_enrich_product_edit
                params:
                    - id
            texmaster_view:
                type: url
                route: textmaster_open_blank_to_project
                params:
                    - projectIdentifier
                    - documentIdentifier
        actions:
            edit_attributes:
                launcherOptions:
                    className: AknIconButton AknIconButton--small AknIconButton--edit
                type:      navigate
                label:     Edit attributes of the product
                link: edit_product
                rowAction: false
            texmaster_view:
                launcherOptions:
                    className: AknIconButton AknIconButton--small AknIconButton--view
                type:      open-blank
                label:     pim_textmaster.action.show_on_textmaster
                link:      texmaster_view
                rowAction: false
        sorters:
            columns:
                productIdentifier:
                    data_name: d.productIdentifier
                productLabel:
                    data_name: d.productLabel
                language:
                    data_name: d.language
                status:
                    data_name: d.status
                updatedAt:
                    data_name: d.updatedAt
            default:
                label: '%oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC'
        filters:
            columns:
                productIdentifier:
                    type:      string
                    label:     pim_textmaster.field.label.product_identifier
                    data_name: d.productIdentifier
                productLabel:
                    type:      string
                    label:     pim_textmaster.field.label.product_label
                    data_name: d.productLabel
                language:
                    type:      string
                    label:     pim_textmaster.field.label.language
                    data_name: d.language
                status:
                    type:      string
                    label:     pim_textmaster.field.label.status
                    data_name: d.status
                updatedAt:
                    type:             date
                    label:            pim_textmaster.field.label.updated_at
                    data_name:        d.updatedAt
                    filter_by_having: true