datagrid:
    document-grid:
        options:
            entityHint: document
            manageFilters: false
        source:
            type:               pim_datasource_default
            entity:             Pim\Bundle\TextmasterBundle\Entity\Document
            repository_method:  createDatagridQueryBuilder
        columns:
            productIdentifier:
                label: pim_textmaster.field.label.product_identifier
            productLabel:
                label: pim_textmaster.field.label.product_label
            languageFrom:
                label: pim_textmaster.field.label.language_from
                type: twig
                template: PimTextmasterBundle:Property:flag.html.twig
                frontend_type: html
            languageTo:
                label: pim_textmaster.field.label.language_to
                type: twig
                template: PimTextmasterBundle:Property:flag.html.twig
                frontend_type: html
            status:
                label: pim_textmaster.field.label.status
                type: twig
                template: PimTextmasterBundle:Property:status.html.twig
                frontend_type: html
            updatedAt:
                label: pim_textmaster.field.label.updated_at
                type: twig
                template: PimTextmasterBundle:Property:date.html.twig
                frontend_type: html
        properties:
            edit_product:
                type: url
                route: pim_enrich_product_edit
                params:
                    - id
            texmaster_view:
                type: url
                route: textmaster_open_blank_to_project
                params:
                    - projectId
                    - textmasterDocumentId
        actions:
            edit_attributes:
                launcherOptions:
                    className: AknIconButton AknIconButton--small AknIconButton--edit
                type:      navigate
                label:     Edit attributes of the product
                link:      edit_product
                rowAction: false
            texmaster_view:
                launcherOptions:
                    className: AknIconButton AknIconButton--small AknIconButton--view
                type:      open-blank
                label:     pim_textmaster.action.show_on_textmaster
                link:      texmaster_view
                rowAction: false
        sorters:
            columns:
                productIdentifier:
                    data_name: d.productIdentifier
                productLabel:
                    data_name: d.productLabel
                languageFrom:
                    data_name: d.languageFrom
                languageTo:
                    data_name: d.languageTo
                status:
                    data_name: d.status
                updatedAt:
                    data_name: d.updatedAt
            default:
                label: '%oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC'
        filters:
            columns:
                productIdentifier:
                    type:      string
                    label:     pim_textmaster.field.label.product_identifier
                    data_name: d.productIdentifier
                productLabel:
                    type:      string
                    label:     pim_textmaster.field.label.product_label
                    data_name: d.productLabel
                languageFrom:
                    type:      choice
                    label:     pim_textmaster.field.label.language_from
                    data_name: d.languageFrom
                    options:
                        field_options:
                            multiple: true
                            choices:  '@pim_textmaster.provider.datagrid->getLangageChoices'
                languageTo:
                    type:      choice
                    label:     pim_textmaster.field.label.language_to
                    data_name: d.languageTo
                    options:
                        field_options:
                            multiple: true
                            choices:  '@pim_textmaster.provider.datagrid->getLangageChoices'
                status:
                    type:      choice
                    label:     pim_textmaster.field.label.status
                    data_name: d.status
                    options:
                        field_options:
                            multiple: true
                            choices:  '@pim_textmaster.provider.datagrid->getStatusChoices'
                updatedAt:
                    type:             date
                    label:            pim_textmaster.field.label.updated_at
                    data_name:        d.updatedAt
                    filter_by_having: true
