# Textmaster extension configuration
pim_textmaster:
    settings:
        api_key:
            value: your_api_key
            scope: app
        api_secret:
            value: your_api_secret
            scope: app
        attributes:
            value: ~
            scope: app
        autolaunch:
            value: false
            scope: app

monolog:
    channels: ['textmaster']
    handlers:
        textmaster:
            type:  stream
            path:  %kernel.logs_dir%/textmaster_%kernel.environment%.log
            level: info
            channels: textmaster
