services:
    pim_textmaster.mass_edit.job.start_projects:
        class: '%pim_connector.job.simple_job.class%'
        arguments:
            - 'textmaster_start_projects'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            -
                - '@pim_textmaster.step.prepare_projects'
                - '@pim_textmaster.step.add_documents'
                - '@pim_textmaster.step.flag_projects_to_send'
        tags:
            -
                name: 'akeneo_batch.job'
                connector: '%pim_enrich.connector_name.mass_edit%'
                type: '%pim_enrich.job.mass_edit_type%'

    pim_textmaster.mass_edit.job.job_parameters.default_values_provider.start_projects:
        class: 'Akeneo\Pim\Enrichment\Component\Product\Connector\Job\JobParameters\DefaultValueProvider\ProductMassEdit'
        arguments:
            - ['textmaster_start_projects', 'textmaster_configure_projects']
        tags:
            - { name: akeneo_batch.job.job_parameters.default_values_provider }

    pim_textmaster.mass_edit.job.job_parameters.constraint_collection_provider.start_projects:
        class: 'Akeneo\Pim\Enrichment\Component\Product\Connector\Job\JobParameters\ConstraintCollectionProvider\ProductMassEdit'
        arguments:
            - ['textmaster_start_projects', 'textmaster_configure_projects']
        tags:
            - { name: akeneo_batch.job.job_parameters.constraint_collection_provider }
