parameters:
    pim_textmaster.processor.denormalization.document.class: 'Pim\Bundle\TextmasterBundle\Processor\Denormalization\DocumentProcessor'

services:
    _defaults:
        public: true

    pim_textmaster.processor.denormalization.document:
        class: '%pim_textmaster.processor.denormalization.document.class%'
        arguments:
            - '@pim_textmaster.provider.locale'
            - '@pim_textmaster.builder.project'
            - '@pim_textmaster.manager.document'
            - '@pim_textmaster.manager.project'
            - '@akeneo_storage_utils.doctrine.object_detacher'
