parameters:
    pim_textmaster.provider.datagrid.class: 'Pim\Bundle\TextmasterBundle\Provider\DatagridProvider'
    pim_textmaster.provider.locale.class:   'Pim\Bundle\TextmasterBundle\Provider\LocaleProvider'

services:
    _defaults:
        public: true

    pim_textmaster.provider.datagrid:
        class: '%pim_textmaster.provider.datagrid.class%'
        arguments:
            - '@pim_localization.translator'
            - '@pim_textmaster.repository.webapi'
            - '@pim_catalog.repository.locale'
            -
    pim_textmaster.provider.locale:
        class: '%pim_textmaster.provider.locale.class%'
