config:
    paths:
        textmaster/system/configuration: pimtextmaster/js/form/system
        textmaster/template/system/group/configuration: pimtextmaster/js/templates/system/group/configuration.html

        textmaster/mass_edit: pimtextmaster/js/mass_edit/textmaster_mass_edit
        textmaster/template/mass_edit: pimtextmaster/js/templates/mass_edit/textmaster_mass_edit.html

        textmaster/controller/dashboard: pimtextmaster/js/controller/dashboard
        textmaster/form/dashboard: pimtextmaster/js/form/dashboard-view
        textmaster/template/form/dashboard: pimtextmaster/js/templates/form/dashboard-view.html
        textmaster/form/dashboard/status: pimtextmaster/js/form/dashboard/status
        textmaster/template/form/dashboard/status: pimtextmaster/js/templates/form/dashboard/status.html

        oro/datagrid/open-blank-action: pimtextmaster/js/datagrid/action/open-blank-action

    config:
        pim/fetcher-registry:
            fetchers:
                textmaster-api-templates:
                    module: pim/base-fetcher
                    options:
                        urls:
                            list: textmaster_rest_api-templates
                textmaster-dashboard-status-data:
                    module: pim/base-fetcher
                    options:
                        urls:
                            list: textmaster_rest_dashboard_status_data
                textmaster-open-blank-to-project:
                    module: pim/base-fetcher
                    options:
                        urls:
                            get: textmaster_rest_dashboard_status_data
        pim/controller-registry:
            controllers:
                textmaster_rest_dashboard:
                    module: textmaster/controller/dashboard
                    config:
                        entity: project
