parameters:
    pim_textmaster.saver.document.class: 'Akeneo\Tool\Bundle\StorageUtilsBundle\Doctrine\Common\Saver\BaseSaver'
    pim_textmaster.saver.project.class:  'Akeneo\Tool\Bundle\StorageUtilsBundle\Doctrine\Common\Saver\BaseSaver'

services:
    pim_textmaster.saver.project:
        class: '%akeneo_storage_utils.saver.base.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@event_dispatcher'
            - '%pim_textmaster.entity.project.class%'

    pim_textmaster.saver.document:
        class: '%akeneo_storage_utils.saver.base.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@event_dispatcher'
            - '%pim_textmaster.entity.document.class%'