services:
    pim_textmaster.updater.document.product:
        class: 'Pim\Bundle\TextmasterBundle\Updater\ProductUpdater'
        arguments:
            - '@pim_catalog.repository.product'
            - '@pim_catalog.updater.product'

    pim_textmaster.updater.document.product_model:
        class: 'Pim\Bundle\TextmasterBundle\Updater\ProductModelUpdater'
        arguments:
            - '@pim_catalog.repository.product_model'
            - '@pim_catalog.updater.product_model'
